sonar.projectKey=bitwarden-eso-provider
sonar.projectName=bitwarden-eso-provider
sonar.sourceEncoding=UTF-8

sonar.sources=crates,deploy,docs,.github,Dockerfile,README.md

sonar.exclusions=target/**,.git/**,**/*.lock
