apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-database
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: SecretStore
  target:
    name: app-database
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: example/app-database
        property: DATABASE_URL
