apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: bitwarden
spec:
  provider:
    webhook:
      url: "http://bweso-bitwarden-eso-provider.bweso-system.svc.cluster.local:8080/v1/resolve"
      method: POST
      headers:
        Content-Type: application/json
      body: |
        {
          "remoteRef": {
            "key": "{{ .remoteRef.key }}",
            "property": "{{ .remoteRef.property }}"
          }
        }
      result:
        jsonPath: "$.data.value"
      timeout: 10s
