{{- if and .Values.caBundle.pem (not .Values.caBundle.existingSecret.name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bweso.fullname" . }}-ca-bundle
  labels:
    {{- include "bweso.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.pem: |
{{ .Values.caBundle.pem | indent 4 }}
{{- end }}
