apiVersion: v2
name: vaultwarden-secrets-operator
description: External Secrets Operator webhook provider for Vaultwarden and Bitwarden Password Manager vaults.
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/ponchia/vaultwarden-secrets-operator
sources:
  - https://github.com/ponchia/vaultwarden-secrets-operator
maintainers:
  - name: Zeno Rocha
    url: https://github.com/ponchia
keywords:
  - vaultwarden
  - bitwarden
  - external-secrets
  - kubernetes
  - secrets
